"""Generate site/lots-catalog.js from the transcribed source table.

The JSON parts under proto/ are the single source of truth (the
Hellenistic lots table, transcribed 2026-10-03). Names tie to
CALCULATIONS: rows sharing (personal point, significator, trigger, sect
rule) collapse into one calculation; each attested name keeps its own
entry with its sources. Run: python3 proto/gen_lots_catalog.py
"""
import json, glob

files = ['proto/lots_catalog.json'] + sorted(glob.glob('proto/lots_catalog_p[0-9].json'))
rows = []
for f in files:
    d = json.load(open(f))
    rows.extend(d['entries'] if isinstance(d, dict) else d)

calcs, calc_ids, names = [], {}, []
for i, r in enumerate(rows):
    key = json.dumps([r[2], r[3], r[4], r[5]], sort_keys=True)
    if key not in calc_ids:
        calc_ids[key] = len(calcs)
        calcs.append({'pp': r[2], 'sig': r[3], 'trig': r[4], 'rev': r[5]})
    names.append({'id': f'hl{i}', 'name': r[0], 'alts': r[1], 'calc': calc_ids[key],
                  'prim': r[6], 'sec': r[7], 'cat': r[8], 'note': r[9]})

def js(v):
    return json.dumps(v, ensure_ascii=False)

out = []
out.append('// lots-catalog.js — the Hellenistic lots registry (generated).')
out.append('//')
out.append('// GENERATED by proto/gen_lots_catalog.py from the transcribed')
out.append('// source table (proto/lots_catalog*.json). Do not edit by hand;')
out.append('// edit the JSON and regenerate.')
out.append('//')
out.append('// Model: a set of CALCULATIONS (personal point + significator -')
out.append('// trigger, with a sect rule) and NAMES tied to them. Names sharing')
out.append('// a calculation are one point under several attestations; one name')
out.append('// with several calculations is a family of variants, each with its')
out.append('// own sources. Operand tokens: planet names; Asc MC IC Dsc; h2 h8')
out.append('// h9 (whole-sign house cusps); Fortune Spirit; Syzygy (prenatal')
out.append('// lunation); rulerAsc ruler2 ruler9 rulerIC rulerSyzygy (domicile')
out.append('// lord of that sign); ["fix", deg] a fixed ecliptic longitude; or')
out.append('// {day:[sig,trig], night:[sig,trig]} for sect-paired formulas.')
out.append('// rev: reverse (swap at night) | fixed | horizon (always below')
out.append('// horizon) | both (use both directions) | dayOnly | nightOnly |')
out.append('// sectPair.')
out.append('')
out.append('/** @typedef {{pp: *, sig: *, trig: *, rev: string}} LotCalculation */')
out.append('/** @typedef {{id: string, name: string, alts: string[], calc: number, prim: string, sec: string, cat: string, note: string}} CatalogLot */')
out.append('')
out.append('/** @type {LotCalculation[]} */')
out.append('export const LOT_CALCULATIONS = [')
for c in calcs:
    out.append(f"  {{ pp: {js(c['pp'])}, sig: {js(c['sig'])}, trig: {js(c['trig'])}, rev: {js(c['rev'])} }},")
out.append('];')
out.append('')
out.append('/** @type {CatalogLot[]} */')
out.append('export const CATALOG_LOTS = [')
for n in names:
    out.append(f"  {{ id: {js(n['id'])}, name: {js(n['name'])}, alts: {js(n['alts'])}, calc: {n['calc']}, prim: {js(n['prim'])}, sec: {js(n['sec'])}, cat: {js(n['cat'])}, note: {js(n['note'])} }},")
out.append('];')
out.append('')

open('site/lots-catalog.js', 'w').write('\n'.join(out))
print(f"wrote site/lots-catalog.js: {len(names)} names, {len(calcs)} calculations")
